#!/bin/bash
# TDS Post Remove Script

SERVICE_NAME="tds"
APP_DIR="/opt/caps"
USER_NAME="tds"

# Remove upstarts
rm /etc/init/nginx.conf
rm /etc/init/juggernaut.conf
rm /etc/init/sidekiq.conf

# Remove Bash variables
# sed 's/PATH//g' ~/.bashrc

# Remove symbolic link to tools
unlink tds

# Remove dependencies
apt-get install -f

# Uninstall nginx-passenger
# ?

# Uninstall gems
gem uninstall passenger
gem uninstall bundler

